### ISSUE TITLE
Repo releases?

### ISSUE THREAD

**Issue by tsilvs** [Lennart1978/servicegui#1]
I like what you did here, I understand this desire to add user-friendly tools to Linux systems.

What do you think about releasing this package in major systems repos, like Debian, Ubuntu, Fedora and Arch?

Or maybe as a flatpak, which is simpler to maintain.

**Comment by Lennart1978** [comment]
Thank you ! Nice to here that someone can use this tool. - Yes, it's a good idea to release it to the systems repos, but I never did this before and don't know how. I also planned to rewrite everything in C with gtk4 plus some extra feautures, but this will take some time. The Fyne GUI Toolkit for Go is a little bis slow and still hast lots of errors.
If you like / want and know how, you may release ServiceGUI to the systems repos (Flatpak) I would strongly support that

Have a nice day
